redis:
  url: 127.0.0.1
  port: 6379
  db: 0
rabbitmq:
  vhost: "/"
  username: guest
  password: guest
  host: 127.0.0.1

# 下面是任务的描述
tasks:
  -
    type: json
    url: 'http://league.vpgame.com/das/data/schedule/allGameSchedule?is_all=false&interval=3&game_type=dota'
    period: 1
    enable: true
    params:
      date: date        # key date & type date
